[font.normal]
family = "Comic Code"
style = "Regular"

[font]
size = 15.0

[font.offset]
x = 0
y = -2

# 0x Default colors
[colors.primary]
background = '#300a24'
foreground = '#eeeeec'

# 0x Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#bbbbbb'
cursor = '#b4d5ff'

# 0x Normal colors
[colors.normal]
black   = '#2e3436'
red     = '#cc0000'
green   = '#4e9a06'
yellow  = '#c4a000'
blue    = '#3465a4'
magenta = '#75507b'
cyan    = '#06989a'
white   = '#d3d7cf'

# 0x Bright colors
[colors.bright]
black   = '#555753'
red     = '#ef2929'
green   = '#8ae234'
yellow  = '#fce94f'
blue    = '#729fcf'
magenta = '#ad7fa8'
cyan    = '#34e2e2'
white   = '#eeeeec'

# [colors.primary]
# background = '#f8f8f8'
# foreground = '#2a2b33'

# [colors.normal]
# black   = '#000000'
# red     = '#de3d35'
# green   = '#3e953a'
# yellow  = '#d2b67b'
# blue    = '#2f5af3'
# magenta = '#a00095'
# cyan    = '#3e953a'
# white   = '#bbbbbb'

# [colors.bright]
# black   = '#000000'
# red     = '#de3d35'
# green   = '#3e953a'
# yellow  = '#d2b67b'
# blue    = '#2f5af3'
# magenta = '#a00095'
# cyan    = '#3e953a'
# white   = '#ffffff'

# # Default colors
# colors:
#   primary:
#     background: '#282828'
#     foreground: '#d4be98'

# # Normal colors
# colors:
#   normal:
#     black: '#3c3836'
#     red: '#ea6962'
#     green: '#a9b665'
#     yellow: '#d8a657'
#     blue: '#7daea3'
#     magenta: '#d3869b'
#     cyan: '#89b482'
#     white: '#d4be98'

# # Bright colors (same as normal colors)
# colors:
#   bright:
#     black: '#3c3836'
#     red: '#ea6962'
#     green: '#a9b665'
#     yellow: '#d8a657'
#     blue: '#7daea3'
#     magenta: '#d3869b'
#     cyan: '#89b482'
#     white: '#d4be98'

# colors:
#   name: 3024 (dark)
#   author: Chris Kempson
#   primary:
#     background: "#090300"
#     foreground: "#a5a2a2"
#   cursor:
#     text: "#090300"
#     cursor: "#a5a2a2"
#   normal:
#     black: "#090300"
#     red: "#db2d20"
#     green: "#01a252"
#     yellow: "#fded02"
#     blue: "#01a0e4"
#     magenta: "#a16a94"
#     cyan: "#b5e4f4"
#     white: "#a5a2a2"
#   bright:
#     black: "#5c5855"
#     red: "#db2d20"
#     green: "#01a252"
#     yellow: "#fded02"
#     blue: "#01a0e4"
#     magenta: "#a16a94"
#     cyan: "#b5e4f4"
#     white: "#f7f7f7"

# # Colors (Base16 Default Dark)
# colors:
#   # Default colors
#   primary:
#     background: '0x181818'
#     foreground: '0xd8d8d8'

#   # Colors the cursor will use if `custom_cursor_colors` is true
#   cursor:
#     text: '0xd8d8d8'
#     cursor: '0xd8d8d8'

#   # Normal colors
#   normal:
#     black:   '0x181818'
#     red:     '0xab4642'
#     green:   '0xa1b56c'
#     yellow:  '0xf7ca88'
#     blue:    '0x7cafc2'
#     magenta: '0xba8baf'
#     cyan:    '0x86c1b9'
#     white:   '0xd8d8d8'

#   # Bright colors
#   bright:
#     black:   '0x585858'
#     red:     '0xab4642'
#     green:   '0xa1b56c'
#     yellow:  '0xf7ca88'
#     blue:    '0x7cafc2'
#     magenta: '0xba8baf'
#     cyan:    '0x86c1b9'
#     white:   '0xf8f8f8'

# colors:
#   primary:
#     background: '0xf8f8f8'
#     foreground: '0x2a2b33'

#   normal:
#     black:   '0x000000'
#     red:     '0xde3d35'
#     green:   '0x3e953a'
#     yellow:  '0xd2b67b'
#     blue:    '0x2f5af3'
#     magenta: '0xa00095'
#     cyan:    '0x3e953a'
#     white:   '0xbbbbbb'

#   bright:
#     black:   '0x000000'
#     red:     '0xde3d35'
#     green:   '0x3e953a'
#     yellow:  '0xd2b67b'
#     blue:    '0x2f5af3'
#     magenta: '0xa00095'
#     cyan:    '0x3e953a'
#     white:   '0xffffff'
